const tree_namespace = require("nary-tree-mab")
const tap = require("tap")

tree = new tree_namespace.NaryTree()
tap.equals(null, tree.root())
const node = tree.create_node(null, "asdf", [])
const root = tree.root()
const tree_object = node.tree()

node.data = "xyz"

const child1 = tree.create_node(tree.root_id, "1234")
child1.add_child("1010")
child1.add_child("1011")
child1.add_child("1012")
child1.add_child("1013")
child1.add_child("1014")
const children_of_1 = child1.get_children()
tap.ok(children_of_1.length === 5)

const child5 = tree.node(5)
child5.add_child("5010")
child5.add_child("5011")
child5.add_child("5012")
child5.add_child("5013")
child5.add_child("5014")
child5.add_child("5015")
const children_of_5 = child5.get_children()
tap.ok(children_of_5.length === 6)
tap.ok(children_of_5[1].data === "5011")

const child11 = tree.node(11)
const child11_path = child11.path()
tap.ok(child11_path[0] === 0)
tap.ok(child11_path[1] === 1)
tap.ok(child11_path[2] === 5)
tap.ok(child11_path[3] === 11)
console.log(child11_path)

const child11_path_with_callback = child11.path( (item) => item.id + "::" + item.data )
tap.ok( child11_path_with_callback )
tap.ok( child11_path_with_callback[0] === "0::xyz" )

tree.remove_node(child1.id)
tap.ok(undefined === tree.node(child1.id))
